name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)

  BUILD_TYPE: Release

jobs:
  compiler:
    name: "Compiler (${{ matrix.os }}, node ${{ matrix.node_version }})"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu"]
        node_version: ["lts_latest"]
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: apt install
        run: sudo apt-get install -y clang clang-tidy
      - name: Install npm dependencies
        run: npm install
      - name: spell check
        run: npm run spell
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: bundle
        run: |
          npm run bundle
          node bin/Cli.js -f fixture/asc1.ts -o build/asc2.hpp
          diff build/asc2.hpp build/asc1.hpp
          node bin/Cli.js -f fixture/asc.compiler.ts -o build/asc2.compiler.ts.hpp --compiler --namespace "testNamespace" --headerIdentifier "__TEST_HEADER_IDENTIFIER__"  
          diff build/asc2.compiler.ts.hpp build/asc.compiler.ts.hpp
