name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)

  BUILD_TYPE: Release

jobs:
  compiler:
    name: "Compiler (${{ matrix.os }}, node ${{ matrix.node_version }})"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu"]
        node_version: ["lts_latest"]
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: apt install
        run: sudo apt-get install -y clang clang-tidy
      - name: Install npm dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Check
        run: npm run lint
      - name: Test
        run: npm run coverage
